# Generated by Django 6.0 on 2026-06-04 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_sast', '0001_initial'),
        ('facility', '0484_remove_facility_discount_codes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SASTHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('code', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sast_hospitals', to='facility.facility')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SASTUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('history', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict)),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('care_user', models.ForeignKey(db_column='care_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='sast_users', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='care_sast.sasthospital')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sasthospital',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('code',), name='unique_sast_hospital_code'),
        ),
        migrations.AddConstraint(
            model_name='sasthospital',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('facility',), name='unique_sast_hospital_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='sastuser',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('hospital', 'user_id'), name='unique_sast_user_id_per_hospital'),
        ),
        migrations.AddConstraint(
            model_name='sastuser',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('hospital', 'care_user'), name='unique_sast_user_per_hospital'),
        ),
    ]
